### ISSUE TITLE
[Mobile]: BUG: APNS token has not yet been set

### ISSUE THREAD

**Issue by novas1r1** [socialincome-san/public#812]
flutter: ----------------FIREBASE CRASHLYTICS----------------
flutter: [firebase_messaging/apns-token-not-set] APNS token has not been set yet. Please ensure the APNS token is available by calling `getAPNSToken()`.
flutter: 
#0      MethodChannelFirebaseMessaging._APNSTokenCheck (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:138:9)
<asynchronous suspension>
#1      MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:244:5)
<asynchronous suspension>
#2      MessagingRepository.initNotifications (package:app/data/repositories/messaging_repository.dart:29:5)
<asynchronous suspension>
#3      SettingsCubit.initMessaging (package:app/core/cubits/settings/settings_cubit.dart:21:7)
<asynchronous suspension>
flutter: ----------------------------------------------------

**Comment by KarinBerg** [comment]
Should be fixed with https://github.com/socialincome-san/public/issues/538
